script: 'ruby -e "p RUBY_VERSION"; true && rake test'
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - rbx
  - jruby
matrix:
  exclude:
    - rvm: rbx
branches:
  only: master
notifications:
  email: false
  webhooks: 
    - http://www.postbin.org/13ztk0c
  campfire:
    secure: óû6ã"¸${gXªçÜ∑’ÄêØﬁ#œ3äªF†;.|ØÀävò5ÛN«1°*ô»l›+`dﬂŒgˆ√cL˛ª"mUàJ˘}“ÎwÖøØ«ƒßñòC±[ÆÈ‹ŸÜÈ∫[)Ω·`ùÀøìŸÙÆ—ü{è*@∞ÔeÓ<´º Ø#