script: 'ruby -e "p RUBY_VERSION"; true && rake test'
rvm:
  - 1.8.7
  - 1.9.2
  - rbx
matrix:
  exclude:
    - rvm: rbx
branches:
  only: master
notifications:
  irc: irc.freenode.net#travis
  # recipients: svenfuchs@artweb-design.de
  email:
    on_success: always
    recipients:
    - svenfuchs@artweb-design.de
