script: 'ruby -e "p RUBY_VERSION"; true && rake test'
after_script:
  - 'echo $TRAVIS_JOB_ID'
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
matrix:
  allow_failures:
    - rvm: 1.9.3
branches:
  only: master
notifications:
  email: me@svenfuchs.com
  webhooks:
    urls:
      - "http://requestb.in/meprbime"
    include_logs: false
