script: 'ruby -e "p RUBY_VERSION"; true && rake test'
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
matrix:
  exclude:
    - rvm: rbx
  allow_failures:
    - rvm: 1.9.3
branches:
  only: master
notifications:
  email: contact@travis-ci.org
  webhooks: 
   - http://www.postbin.org/13ztk0c
  campfire:
   secure: "gqmdwaO/1/Xz6nlAJaf1ahqPFKHXplTuesIFGyMEGXpf7b5eOiVxZBIWdNZl\n+6hl5lQYHLSzMsqq9aJ2gLPjZS270eursFKP6PkvYHfaRHrEimiAxWN8wt0i\n8ekN8NNuFUcUyZ3Ru9WrF5yaFa6U+oW+HbxQlDX/+7RDTfkpCuA="
