script: 'ruby -e "p RUBY_VERSION"; true && rake test'
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
matrix:
  exclude:
    - rvm: rbx
  allow_failures:
    - rvm: 1.9.3
branches:
  only: master
notifications:
  email: contact@travis-ci.org
  webhooks: 
   - http://www.postbin.org/13ztk0c
