rvm:
  #- 1.8.7
  #- 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby-head

env:
  matrix:
    - secure: "Fr8PIJeUV4pPhDJo/8IRbkV9nXQcmxJ7O0epNdR2/n4TsyhXOClLKtiK0yL/\ny8MQhtO16Ey70nvvoNq8w1qvjX6BsQZ1EXCIh4qdKv9xcWEJTI7OsoCYnAPo\ncSUT/kfS/JpRb7A1KvI0IJxo5jwImPm439afD7AjBcFeyt9p6QQ="
    - "BAR=baz"

matrix:
  allow_failures:
    - rvm: 1.9.3
    - "FOO=bar"

before_script:
  - rvm list

script: 'ruby -e "p RUBY_VERSION"; true && rake test'

after_script:
  - 'echo $TRAVIS_JOB_ID'

branches:
  only: master

notifications:
  email: false
