script: 'ruby -e "p RUBY_VERSION"; true && rake test'
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - rbx
  - jruby
matrix:
  exclude:
    - rvm: rbx
branches:
  only: master
notifications:
  email: false
  # webhooks: 
  #   - http://www.postbin.org/13ztk0c
  campfire:
    secure: "`\x04\x9E^\x89\x18\xBCn\x89ew\xB3\xBAm@\x96\f(\xEF\xCF\x98\xCA\x01\x04R/\b\x19@\x1A\xDF\x00\t\x11\xBB\xB1\r\xCE\xDD\xEB\x03\xEF\xAD1[QYFCe\xA7\xC5>\xFF?\xDDN~\x0E,\xB9\xDD\x17\x86f#\xBD\xF0n\x83\xE0@\vy\xECw\xF8p]<\xB9\xD3C\xCB\xE8\eZ\x85\x89:S\x06\r\x14$I\xC4\x82\xB4\xDA\x92\xB3\x16\x82]\xABD'\xBB\xB5\xA1\eM\xA1[.\xC4\xA0\xE8\xFAK_\xF7\xB0\xD8\x14\xC6\xC5"
