script: 'ruby -e "p RUBY_VERSION"; true && rake test'
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - rbx
  - jruby
matrix:
  exclude:
    - rvm: rbx
branches:
  only: master
notifications:
  email: false
  webhooks: 
    - http://www.postbin.org/13ztk0c
  campfire:
    secure: "=^P\xC9G\xCD\xF7.\xB0Q\xBC\x16.\xC3\xC5\xA6_N\xCB\a\xCC/\xF479aYU|\x87\xD1\x97\x84\xF6\xDF\xB0\v'\x86\xEB\r\x9D\xE1\xE8_m^@H:\xEB\xE3\xC8,\xF0\xAAdX]Cn\x8A\xE8f,\xB2.\xF2Q\x8B\x8FzOwQ\x12*k\x89\x1A\x1Fq\x03\xE2\xCC\xD0\x8D\xD2\xC1\x9A\x86T.\xC2a\x8E\xD1\xDAc\"\xC7\xE0hC\xC1\xBF\x8E\x19.\xB0?\x06\xC7\x0E\xDC,\xF2\x17\x04\xA5$\x83\f\x88\t/CI"