script: 'ruby -e "p RUBY_VERSION"; true && rake test'
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - rbx
  - jruby
matrix:
  exclude:
    - rvm: rbx
branches:
  only: master
notifications:
  email: false
  # webhooks: 
  #   - http://www.postbin.org/13ztk0c
  campfire:
    secure: "\x12\xDC\x1E\e Z\xBCC\x13\xC5|\xF25\xE1\xB7\x16l=l\xB5\xE9ck\xDDxLhA\n\xE9\xE2\v\xF9\x9A;K\xDA\xA6\x01\xF4%\x0F\xEE\x0E\rZ:\x8D\xF8\xB8\xB9\xE8l\t(\"\xC4\x8A\f?\xF9\xB7\x98\x87\x9F\xA20\xA6\xFE~\xEC\"\xC43\x16um\x99\\\"\xA4\xEC\xA30\x1A\x1Dx\x9B}\xA9U\x92\x06\x94\x1E\x98\xAB\xDE2\a\xDD\xA1\x81\x05N\xF4\xC7\x97\xA37w\x19\x99@\xAF1#\xDA\x8A\x1DS\xED*\x17i\x99;P"
