script: 'ruby -e "p RUBY_VERSION"; true && rake test'
rvm:
  - 1.8.7
  - 1.9.2
matrix:
  exclude:
    - rvm: rbx
branches:
  only: master
notifications:
  email: false
  webhooks: http://www.postbin.org/13ztk0c