script: 'ruby -e "p RUBY_VERSION"; true && rake test'
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - rbx
  - jruby
matrix:
  exclude:
    - rvm: rbx
branches:
  only: master
notifications:
  email: false
  # webhooks: 
  #   - http://www.postbin.org/13ztk0c
  campfire:
    secure: f0HoPZAO5EyuAjGswE1xGElGzREvsey/ZlpWGfuqO2a+DmxcIDaR6logJUoK\n3Vne5B6vqDbNjRYRQRIieq4/WMVvxhTYzaojEzmP1ueETl9CDwfbX/Ex65Jb\okQZMxNJcZw5KZOTSzuwMZmYnZ3HK4V46lSLXCL44CGtnJ1OOmY=
